In [196]:

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [197]:
dataset = pd.read_csv('dataf.csv')
X = dataset.iloc[0:, 2:8].values
#X = X.replace(',', '')
#for c in X.split(","):
#X=[float(c) for c in X.split(',')]
  #print float(c)
#y = dataset.iloc[:, 3].values
#dataset.['Company Name']=dataset.['Company Name'].astype(float)
#y = dataset.iloc[:, 1].values
y = dataset.iloc[:, 1:2].values
print(X)
print(y)

[[7.1470380e+04 8.2140000e+01 1.6894150e+04 1.1102170e+04 2.1000000e+00
  1.5894123e+05]
 [4.4144000e+04 7.3550000e+01 3.5163000e+04 5.8340000e+03 1.5700000e+00
  5.2975700e+05]
 [2.1544650e+04 7.6100000e+01 7.1320200e+03 3.6641800e+03 1.2300000e+00
  5.0320540e+04]
 ...
 [          nan           nan           nan           nan           nan
  1.6774450e+04]
 [          nan           nan           nan           nan           nan
  1.6680850e+04]
 [          nan           nan           nan           nan           nan
  1.6348190e+04]]
[[527692.69]
 [371019.  ]
 [297275.05]
 [275197.42]
 [242868.65]
 [123170.  ]
 [109609.42]
 [ 98972.05]
 [ 90307.43]
 [ 86987.86]
 [ 86020.3 ]
 [ 76727.  ]
 [ 75126.3 ]
 [ 73107.  ]
 [ 70610.71]
 [ 69202.76]
 [ 69202.76]
 [ 66967.31]
 [ 63401.19]
 [ 62062.14]
 [ 54985.77]
 [ 53614.  ]
 [ 51310.25]
 [ 49974.11]
 [ 49608.  ]
 [ 48123.8 ]
 [ 46810.34]
 [ 45749.16]
 [ 44995.65]
 [ 43348.04]
 [ 42670.89]
 [ 41338.39]
 [ 40767.81]
 [ 38644.  ]
 [ 38395.43]
 [ 38

In [198]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='median')

In [199]:
from sklearn.impute import SimpleImputer 
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer=imputer.fit(X[:,0:6])
X[:,0:6]=imputer.transform(X[:,0:6])
print(X)


[[7.1470380e+04 8.2140000e+01 1.6894150e+04 1.1102170e+04 2.1000000e+00
  1.5894123e+05]
 [4.4144000e+04 7.3550000e+01 3.5163000e+04 5.8340000e+03 1.5700000e+00
  5.2975700e+05]
 [2.1544650e+04 7.6100000e+01 7.1320200e+03 3.6641800e+03 1.2300000e+00
  5.0320540e+04]
 ...
 [5.2883223e+03 6.2628300e+01 4.3748585e+03 4.4213657e+03 1.9752100e+01
  1.6774450e+04]
 [5.2883223e+03 6.2628300e+01 4.3748585e+03 4.4213657e+03 1.9752100e+01
  1.6680850e+04]
 [5.2883223e+03 6.2628300e+01 4.3748585e+03 4.4213657e+03 1.9752100e+01
  1.6348190e+04]]


In [200]:
from sklearn.impute import SimpleImputer 
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer=imputer.fit(y[:,0:1])
y[:,0:1]=imputer.transform(y[:,0:1])
print(y)

[[527692.69 ]
 [371019.   ]
 [297275.05 ]
 [275197.42 ]
 [242868.65 ]
 [123170.   ]
 [109609.42 ]
 [ 98972.05 ]
 [ 90307.43 ]
 [ 86987.86 ]
 [ 86020.3  ]
 [ 76727.   ]
 [ 75126.3  ]
 [ 73107.   ]
 [ 70610.71 ]
 [ 69202.76 ]
 [ 69202.76 ]
 [ 66967.31 ]
 [ 63401.19 ]
 [ 62062.14 ]
 [ 54985.77 ]
 [ 53614.   ]
 [ 51310.25 ]
 [ 49974.11 ]
 [ 49608.   ]
 [ 48123.8  ]
 [ 46810.34 ]
 [ 45749.16 ]
 [ 44995.65 ]
 [ 43348.04 ]
 [ 42670.89 ]
 [ 41338.39 ]
 [ 40767.81 ]
 [ 38644.   ]
 [ 38395.43 ]
 [ 38224.   ]
 [ 36858.8  ]
 [ 35703.5  ]
 [ 34119.12 ]
 [ 34066.66 ]
 [ 33650.54 ]
 [ 30348.95 ]
 [ 30249.96 ]
 [ 29624.75 ]
 [ 29054.95 ]
 [ 28979.44 ]
 [ 28842.   ]
 [ 28496.77 ]
 [ 27715.97 ]
 [ 27219.6  ]
 [ 26012.   ]
 [ 25309.72 ]
 [ 23943.21 ]
 [ 23286.53 ]
 [ 22638.57 ]
 [ 22261.15 ]
 [ 22071.24 ]
 [ 21118.   ]
 [ 20891.6  ]
 [ 20550.43 ]
 [ 20164.9  ]
 [ 19916.25 ]
 [ 19894.12 ]
 [ 19184.81 ]
 [ 19069.97 ]
 [ 18209.92 ]
 [ 17631.26 ]
 [ 17383.97 ]
 [ 17355.02 ]
 [ 16851.21 ]
 [ 16391.78 ]
 [ 158

In [201]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [202]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)
sc_y = StandardScaler()
y_train = sc_y.fit_transform(y_train)

In [203]:
def clean_dataset(df):
    assert isinstance(df, pd.DataFrame), "df needs to be a pd.DataFrame"
    df.dropna(inplace=True)
    indices_to_keep = ~df.isin([np.nan, np.inf, -np.inf]).any(1)
    return df[indices_to_keep].astype(np.float64)

In [204]:
clean_dataset(dataset)

0        0.1       0.2    0.3       0.4       0.5    0.6        0.7
0   0.0  527692.69  71470.38  82.14  16894.15  11102.17   2.10  158941.23
1   0.0  371019.00  44144.00  73.55  35163.00   5834.00   1.57  529757.00
2   0.0  297275.05  21544.65  76.10   7132.02   3664.18   1.23   50320.54
3   0.0  275197.42  20193.42  77.84   6028.66   2938.48   1.07   39869.30
6   0.0  109609.42   7749.17  46.42  26715.79  12113.03  11.05  185075.44
8   0.0   90307.43   7988.02  43.02  11749.89   4779.89   5.29  201121.02
10  0.0   86020.30   3325.70  57.19   7500.60   3254.90   3.78   42713.40
11  0.0   76727.00  10599.00  46.03   8259.00   1400.00   1.82   58826.00
12  0.0   75126.30   2321.91  30.56   6025.67   1778.37   2.37   39494.57
14  0.0   70610.71  11255.34  84.40  10533.19   5131.06   7.27   91939.23
15  0.0   69202.76   4662.00  50.57   2020.60   4273.10   6.17   33793.67
16  0.0   69202.76   4662.00  50.57   2020.60   4273.10   6.17   33793.67
17  0.0   66967.31  19441.80  80.48   2178.82   8830.34  13.19   69777.05
21  0.0   53614.00   3839.27  33.34   4796.04   2980.22   5.56   30738.24
27  0.0   45749.16  11394.46  75.46   1205.43   1981.71   4.33   61758.83
28  0.0   44995.65   7587.24  50.57  12464.32   2728.44   6.06   51638.94
37  0.0   35703.50   3273.62  54.60   2455.72   1926.01   5.39   40557.27

In [205]:
from sklearn.linear_model import LinearRegression
#np.where(x.values >= np.finfo(np.float64).max)
regressor = LinearRegression()
np.any(np.isnan(X_train))
np.all(np.isfinite(X_train))
np.any(np.isnan(y_train))
np.all(np.isfinite(y_train))
print(X_train)
print(y_train)
regressor.fit(X_train, y_train)


[[ 0.32857583 -0.40549641  0.2026742   0.03268239 -0.01302966 -0.25686761]
 [-0.4087172  -0.5258173  -0.89892213 -0.72224693 -0.85661095  0.00179126]
 [-0.66605151 -1.36528155 -0.35795576  0.03268239 -0.01302966  0.00179126]
 ...
 [-0.46061365  1.62465781  0.00879584  0.03268239 -0.01302966  0.00179126]
 [-0.04252141  0.00959676  0.00879584 -0.26300988 -0.60196219  0.00179126]
 [-0.04252141  0.00959676 -0.84752706 -0.71180444  0.82353194  0.00179126]]
[[-2.00096238e-01]
 [-6.20083068e-01]
 [-7.68807521e-03]
 [-7.68807521e-03]
 [-7.68807521e-03]
 [-7.68807521e-03]
 [-7.68807521e-03]
 [-6.47822603e-01]
 [ 3.62637867e-01]
 [-7.68807521e-03]
 [-7.68807521e-03]
 [-7.68807521e-03]
 [-7.68807521e-03]
 [ 3.31504925e-02]
 [-7.68807521e-03]
 [-7.68807521e-03]
 [-3.78067384e-01]
 [-6.25875634e-01]
 [ 3.56066420e+00]
 [-7.68807521e-03]
 [-5.44964408e-01]
 [-7.68807521e-03]
 [-4.70808659e-01]
 [-5.87042091e-01]
 [-4.97145462e-02]
 [-6.74464245e-01]
 [-2.92049912e-01]
 [ 4.34533749e-01]
 [-7.6880752

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [206]:
y_pred = regressor.predict(X_test)

In [207]:
import statsmodels.formula.api as sm

In [208]:
from statsmodels import api as sm

In [209]:
X = np.append(arr = np.ones((230, 1)).astype(int), values = X, axis = 1)
X_opt = X[:, [0, 1, 2, 3, 4]]
regressor_OLS = sm.OLS(endog = y, exog = X_opt).fit()
regressor_OLS.summary()
#X_opt = X[:, [0, 2, 3, 4, 5]]
#regressor_OLS = sm.OLS(endog = y, exog = X_opt).fit()
#regressor_OLS.summary()
#X_opt = X[:, [0, 3, 4, 5]]
#regressor_OLS = sm.OLS(endog = y, exog = X_opt).fit()
#regressor_OLS.summary()
#X_opt = X[:, [0, 3, 5]]
#regressor_OLS = sm.OLS(endog = y, exog = X_opt).fit()
#regressor_OLS.summary()
#X_opt = X[:, [0, 3]]
#regressor_OLS = sm.OLS(endog = y, exog = X_opt).fit()
#regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.709
Model:                            OLS   Adj. R-squared:                  0.703
Method:                 Least Squares   F-statistic:                     136.8
Date:                Sun, 17 May 2020   Prob (F-statistic):           4.63e-59
Time:                        04:00:45   Log-Likelihood:                -2670.8
No. Observations:                 230   AIC:                             5352.
Df Residuals:                     225   BIC:                             5369.
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       8567.2410   8062.264      1.063      0.289   -7319.961    2.45e+04
x1             6.3389      0.353     17.957      0.000       5.643       7.034
x2          -107.2990    124.732     -0.860      0.391    -353.092     138.494
x3             1.5234      0.606      2.514      0.013       0.329       2.718
x4             1.5965      0.386      4.140      0.000       0.837       2.356
==============================================================================
Omnibus:                       84.909   Durbin-Watson:                   0.765
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              791.805
Skew:                           1.144   Prob(JB):                    1.15e-172
Kurtosis:                      11.797   Cond. No.                     4.70e+04
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.7e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""